---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 迷旅.
--- DateTime: 2024/4/15 17:15
---

-- 1.parameters list
local voucherId = ARGV[1]
local userId = ARGV[2]

-- 2. data key
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

-- 3.0 script service
-- 3.1 判断库存是否充足: GET stockKey
if tonumber(redis.call('GET', stockKey)) <= 0 then
    -- 3.2 库存不足，返回1
    return 1
end

-- 3.2 判断用户是否下单: SISMEMBER orderKey userId
if redis.call('SISMEMBER', orderKey, userId) == 1 then
    -- 3.3 存在，说明重复下单，返回2
    return 2
end

-- 3.4 扣减库存: INCRBY stockKey -1
-- 3.5 下单(保存用户) SADD orderKey userId
redis.call('INCRBY', stockKey, -1)
redis.call('SADD', orderKey, userId)

return 0